// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"willowTools","status":true,"description":"random fixes i need.","parameters":{}},
{"name":"SRD_WindowFrameAntiStretch","status":true,"description":"Instead of stretching the frames around windows, this will make window frames repeat.","parameters":{}},
{"name":"EliMZ_Book","status":false,"description":"♦6.1.2♦ Essential plugin for all Eli plugins.","parameters":{"checkVersion":"false","updateErrorPrinter":"true","iterateEventList":"true","engine":"{\"styleOverflow\":\"false\",\"disableEffekseer\":\"false\",\"--- BUG FIXES ---\":\"\",\"fixBitmapStartLoad\":\"true\"}","playtest":"{\"gameFocus\":\"false\",\"enableGameWindowPosition\":\"false\",\"alignX\":\"left\",\"offsetX\":\"10\",\"alignY\":\"center\",\"offsetY\":\"10\",\"openDevTools\":\"false\",\"quickRestart\":\"true\",\"startFps\":\"false\"}"}},
{"name":"DestinationSprite","status":true,"description":"<DestinationSprite> v2.0.5 - Customizable destination sprite for mouse/touch input with spritesheet animation support","parameters":{"spriteType":"Circle","imageName":"","Sprite Settings":"","spriteSize":"32","spriteColor":"#ff00ff","spriteOpacity":"120","blendMode":"Additive","Animation Settings":"","animationMode":"Once","fadeSpeed":"12","scaleAnimation":"true","Spritesheet Settings":"","frameWidth":"48","frameHeight":"48","frameNumber":"8","animationSpeed":"6","loopType":"Forward"}},
{"name":"EliMZ_PixelPerfect","status":false,"description":"♦1.0.0♦ Pixel perfect rendering","parameters":{}},
{"name":"EliMZ_ScreenManager","status":false,"description":"♦1.0.1♦ Manage game scale/fullscreen/resolution","parameters":{"-- Scaling --":"","integerScaling":"false","defaultScale":"1","scaleList":"0","allowFractionalDownscale":"true","scaleKey":"","-- Resolution --":"","resolutionList":"","defaultResolutionIndex":"0","uiAreaFollowScreenSize":"true","hideOverflow":"true","-- Fullscreen --":"","startFullscreen":"false","-- Options --":"","addScaleOption":"true","optionTextScale":"Screen Scale","addFullscreenOption":"false","optionTextFullscreen":"Fullscreen","addResolutionOption":"false","optionTextResolution":"Resolution"}},
{"name":"noshake","status":false,"description":"Make certain pictures not shake with the screen.","parameters":{}},
{"name":"autotileWaterSpeed","status":true,"description":"Adjusts the speed of the animated water autotiles.","parameters":{"speed":"10"}},
{"name":"SmoothTouchMove","status":true,"description":"on touch move, player can through events under the player","parameters":{}}
];
