// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"willowTools","status":true,"description":"random fixes i need.","parameters":{}},
{"name":"SRD_WindowFrameAntiStretch","status":true,"description":"Instead of stretching the frames around windows, this will make window frames repeat.","parameters":{}},
{"name":"DestinationSprite","status":true,"description":"<DestinationSprite> v2.0.5 - Customizable destination sprite for mouse/touch input with spritesheet animation support","parameters":{"spriteType":"Circle","imageName":"","Sprite Settings":"","spriteSize":"32","spriteColor":"#ff00ff","spriteOpacity":"120","blendMode":"Additive","Animation Settings":"","animationMode":"Once","fadeSpeed":"12","scaleAnimation":"true","Spritesheet Settings":"","frameWidth":"48","frameHeight":"48","frameNumber":"8","animationSpeed":"6","loopType":"Forward"}}
];
